# Generated by Django 5.2.17 on 2026-09-28 16:39

import board.models
import board.validators
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_caregiver_approval', models.BooleanField(default=False, help_text='If on, self-registered caregivers cannot sign in until an admin approves them.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +91 98765 43210.', regex='^\\+?[0-9 ()-]{7,20}$')])),
                ('is_primary', models.BooleanField(default=False, help_text='Main point of contact for their patients.')),
                ('is_approved', models.BooleanField(default=True, help_text='Unapproved caregivers cannot sign in to the board.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], default='undisclosed', max_length=20)),
                ('language', models.CharField(default='English', max_length=50)),
                ('condition_type', models.CharField(choices=[('als', 'ALS'), ('cerebral_palsy', 'Cerebral Palsy'), ('stroke', 'Stroke'), ('spinal_cord_injury', 'Spinal Cord Injury'), ('locked_in', 'Locked-in Syndrome'), ('muscular_dystrophy', 'Muscular Dystrophy'), ('parkinsons', "Parkinson's"), ('other', 'Other')], default='other', max_length=30)),
                ('condition_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Updated by the gaze app heartbeat.', null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Account used by the gaze app to call the API (owner of the API token).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('caregiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='board.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_messages', to='board.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientCaregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='secondary', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='board.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to='board.patient')),
            ],
            options={
                'verbose_name': 'patient–caregiver link',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='caregivers',
            field=models.ManyToManyField(blank=True, related_name='patients', through='board.PatientCaregiver', to='board.caregiver'),
        ),
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('report_type', models.CharField(choices=[('doctor_visit', 'Doctor visit'), ('lab', 'Lab'), ('therapy', 'Therapy'), ('discharge', 'Discharge summary'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=board.models.report_upload_to, validators=[board.validators.validate_report_file])),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_added', to='board.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.patient')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('is_emergency', models.BooleanField(default=False)),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, help_text='0–10, filled when the phrase comes from the pain scale.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_requests', to='board.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='board.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='patientcaregiver',
            constraint=models.UniqueConstraint(fields=('patient', 'caregiver'), name='unique_patient_caregiver'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['patient', '-timestamp'], name='request_patient_time_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['is_emergency', 'acknowledged_at'], name='request_alert_idx'),
        ),
    ]
